version: '3.2'
services: 
     mysql_database:
          image: "mysql:latest"
          container_name: mysql
          hostname: mysql
          dns: [172.17.42.1]
          volumes:
            - /var/lib/mediawiki-containers/mysql:/var/lib/mysql:rw
          environment:
            - MYSQL_ROOT_PASSWORD="password"
          restart: always

     mediawiki:
             image: "mediawiki:1.34"
             container_name : mediawiki
             hostname: wiki
             ports:
               - "8080:80"
             dns: [172.17.42.1]
             links:
               - mysql_database
             volumes:
               - /var/lib/mediawiki-containers/mediawiki:/data:rw
               - ./conf/mediawiki:/conf:ro
             environment:
               - MEDIAWIKI_SITE_SERVER=//localhost
               - MEDIAWIKI_SITE_NAME=MediaWiki
               - MEDIAWIKI_SITE_LANG=en
               - MEDIAWIKI_ADMIN_USER=admin
               - MEDIAWIKI_ADMIN_PASS=rosebud
               - MEDIAWIKI_UPDATE=true
               - MEDIAWIKI_VERSION=1.25.3
               - MEDIAWIKI_DB_USER=root
               - MEDIAWIKI_DB_HOST=mysql.docker

    # Link to node services
               - MEDIAWIKI_RESTBASE_URL=http://mediawiki-node-services.docker:7231/localhost/v1
